"""autogen: create initial tables

Revision ID: b3e4f6a5e76a
Revises: 
Create Date: 2025-12-07 02:02:44.304777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e4f6a5e76a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('friend_name', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('pending_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user', sa.String(length=80), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'post', ['shared_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pending_invite', schema=None) as batch_op:
        batch_op.drop_column('to_user')

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('friend_name')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
